name: base_codecs
description: A set of base16 (hex), base32 (Rfc, RfcHex, Crockford, ZBase, GeoHash, WordSafe), Base58 (Bitcoin, Flickr, Ripple) with Base85Check, base85 (Ascii85, Z85, IPv6) codecs
version: 1.0.0
homepage: https://github.com/KirsApps/base_codecs

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: 3.0.1

dev_dependencies:
  lint: ^1.7.2
  test: ^1.16.0
